title: Bishop Challoner RE Department
subtitle: Learn R.E.
description: >- # this means to ignore newlines until "baseurl:"
  RE taught on the internet

# url: "#" # the base hostname & protocol for your site, e.g. https://example.github.io
# baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "192.168.5.245"
urls:
    #- text: Blog
    #  url: /blog
    - text: Contact
      url : /contact
    - text: Start Learning
      url: /start-learning

# Edit these details

# author_logo: profile.png
author: Mrs Cripps
author_bio: Teacher of RE
author_location: UK



# social links
twitter_username: mrscripps


# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-162009399-1

# Choose what to show ( can be true or false)
# show_author_work_experiences: true
# show_author_education_details: true
# show_author_project_details: true


# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
